
  
  export const codeBackup = ()=>{
   
    
      
    
      
    
      function handleEditClick(adminRes: any) {
        setIsEditing(true);
        setCurrentRes({ ...adminRes });
      }

return()
<>
<div></div>
</>

  }
  