POST http://localhost:8000/app/booking
Content-Type: application/json

{
    "AOP": "3",
    "time": "nånting",
    "customerName": "SOFIE",
    "customerEmail": "felix@mail.se",
    "customerNumber": "3432432"
}
